
// This pattern is generated by the _build/pattern-removeNonWord.js script
import {RemoveNonWord} from './constants';

/**
 * Remove non-word chars.
 */
const removeNonWord = (str: string): string => str.replace(RemoveNonWord, '');

export {
    removeNonWord
};
